version: '3.9'

services:
  # Aplicação PHP (Yii2)
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: expenses_app
    restart: unless-stopped
    volumes:
      - .:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/custom.ini
    networks:
      - expenses_network

  # Servidor Web (Nginx)
  nginx:
    image: nginx:1.27-alpine
    container_name: expenses_nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    networks:
      - expenses_network

  # Banco de Dados (MySQL)
  db:
    image: mysql:8.0
    container_name: expenses_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: expenses_db
      MYSQL_USER: expenses_user
      MYSQL_PASSWORD: expenses_pass
    ports:
      - "8236:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - expenses_network

  # phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: expenses_pma
    restart: unless-stopped
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root123
    ports:
      - "8081:80"
    depends_on:
      - db
    networks:
      - expenses_network

volumes:
  db_data:

networks:
  expenses_network:
    driver: bridge